name: 'at-code-checker'
description: 'This code review tool automates analyzing pull requests by retrieving diffs, generating AI feedback, and posting comments to streamline reviews.'
author: 'avila-tek'

# Define your inputs here.
inputs:
  OPEN_AI_KEY:
    description: 'OpenAI API Key used to connect with GPT models for feeding the changes and writting the comments'
    required: true

  GITHUB_TOKEN:
    default: ${{ github.token }}
    description: 'GitHub token used to create the report comment. If not specified, the default GitHub actions token will be used'

branding:
  icon: 'code'
  color: 'green'

runs:
  using: node20
  main: dist/index.js
